[package]
name = "fleet_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = {version = "0.31.1"}
egui_extras = { version = "0.31.1", features = ["default", "image"] }
env_logger = "0.11.8"
uuid = "1.16.0"

[dev-dependencies]
insta = "1.43.0"
